### ISSUE TITLE
UX: Replace current support list with icons

### ISSUE THREAD

**Issue by RichardLitt** [backyourstack/backyourstack#339]
Instead of saying this on the front page:

> * We currently detect dependencies from JavaScript (NPM), PHP (Composer), .NET (Nuget), Go (dep), Ruby (Gem) and Python (Requirement). Want to see more languages? Please see how to contribute.

I think it would be better to show the logos for those languages, so that people can get a better idea of what is supported without reading small text.

**Comment by abitrolly** [comment]
@RichardLitt I don't even see the text on https://backyourstack.com/ Where is it?

**Comment by RichardLitt** [comment]
Not seeing it anymore.
