### ISSUE TITLE
How to enable caching an organization dependencies?

### ISSUE THREAD

**Issue by bzg** [backyourstack/backyourstack#373]
Hi there. I am running a local instance with `npm run start`.

I assumed that setting AWS* environment variables in `.env` would enable caching of an organization dependencies - namely these variables:

    AWS_ACCESS_KEY_ID = "..."
    AWS_SECRET_KEY = "..."
    AWS_S3 _BUCKET = "..."

What is the S3 bucket used for in the application? If it is for caching results, how do I enable this?

My use-case is that I'd like to deploy *locally* and get the dependencies programmatically from `http GET` requests, without being connected via GitHub. Caching would help a lot.

**Comment by znarf** [comment]
S3 is not used for caching, it's only used for the subscription data which is not relevant here.

By default, there is some _in memory_ caching that should make repeating requests efficient. https://github.com/backyourstack/backyourstack/blob/master/src/lib/cache.js

**Comment by bzg** [comment]
Got it, thanks!
