### ISSUE TITLE
Unable to input GitHub id on homepage without being signed in

### ISSUE THREAD

**Issue by RichardLitt** [backyourstack/backyourstack#387]
If you are not signed into GitHub, any entry into the 'Use a GitHub identifier' section comes up as an error. 

<img width="1913" alt="Screen Shot 2020-03-05 at 09 21 32" src="https://user-images.githubusercontent.com/910753/75990308-b9acd700-5ec2-11ea-8deb-1d727b900788.png">

The error incorrectly states "There is no GitHub organization or user with this identifier." for valid identifiers. 

Related to #375.

**Comment by abitrolly** [comment]
@RichardLitt I just checked this from anonymous window and it works as expected.

![image](https://user-images.githubusercontent.com/8781107/130181976-fdfd4d16-3627-416c-b9af-f1b3e7a9e4e5.png)

Maybe there was a problem with API limit?

**Comment by RichardLitt** [comment]
Cannot replicate. I think your guess is probably accurate. Thanks for checking. Closing this.
