### ISSUE TITLE
Move homepage back to previous version

### ISSUE THREAD

**Issue by znarf** [backyourstack/backyourstack#955]
BackYourStack currently have an homepage that looks completely different from the rest of the application.

A lot of time passed since Sustain 2020 and it doesn't seem at this point that we're looking for partnership or beta testers, key points that are featured on this new homepage. Who is actually answering to these emails and what are we doing with it? 

I'm proposing to move back to the previous homepage which is simpler and to the point. https://backyourstack.com/v1

<img width="1435" alt="Screenshot 2021-08-20 at 13 15 30" src="https://user-images.githubusercontent.com/806/130225383-9e518d2b-39e7-4b49-b594-1d6be36fb145.png">

Feedback welcome!

**Comment by piamancini** [comment]
+1
